### ISSUE TITLE
Palindrome chk for string

### ISSUE THREAD

**Issue by LySergicaciD125** [LySergicaciD125/py_beginners#15]
Create a .py file to check if a string input by user is pallindrome or not.
Name file palindrome_string_chk.py

**Comment by Sindhu-321** [comment]
Can I get this task assigned? Thanks.

**Comment by LySergicaciD125** [comment]
Assinged
note: multiple people can be assingned

**Comment by dhruvik-patel** [comment]
Please, Assign me this task.

**Comment by Kunal1198** [comment]
Hi can I work on this
