### ISSUE TITLE
Compound interest calculator

### ISSUE THREAD

**Issue by LySergicaciD125** [LySergicaciD125/py_beginners#16]
Create a compound interest calculator. Take input from user.
Name file as compound_int_cal.py

**Comment by dhruvik-patel** [comment]
Can I work on this?

**Comment by rudhrasekar** [comment]
Can i work on this ,if it is open ?

**Comment by LySergicaciD125** [comment]
It is open submit the pr

**Comment by LySergicaciD125** [comment]
Star the repositry if you find it interesting.
More hacktoberfest issues coming up
