### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by LySergicaciD125** [LySergicaciD125/py_beginners#5]
Improve readme by adding a table of contents

**Comment by er-raoniz** [comment]
Please assign this to me. I would like to contribute on this.

**Comment by LySergicaciD125** [comment]
Assinged

**Comment by LySergicaciD125** [comment]
Start  a pull request when you are done

**Comment by LySergicaciD125** [comment]
More people can be assinged . Best pr will be selected

**Comment by er-raoniz** [comment]
Created [this](https://github.com/LySergicaciD125/py_beginners/pull/17) PR, kindly review and merge it.

**Comment by LySergicaciD125** [comment]
Star the repo and check issues for more hactoberfest issues
